version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: rjgcsj-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shopdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  backend:
    build: 
      context: .  # 构建上下文为项目根目录
      dockerfile: Dockerfile
    container_name: rjgcsj-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data: